#!/bin/bash


find . -name 'mckit*' -print0 | xargs -0 rename --subst-all 'mckit' "$1"; find . -name 'mckit*' -print0 | xargs -0 rename --subst-all 'mckit' "$1"; ack --literal --files-with-matches 'mckit' --print0 | xargs -0 sed -i '' "s/mckit/$1/g"
